storage: ./storage
store: 
  memory:
    limit: 1000
auth:
  htpasswd:
    file: ./htpasswd
web:
  title: Verdaccio Heroku
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $all
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
